function [Usma, Vsma]=InterpolSpMat_R2R_3Duvfield(...
    ArrayBigSma3Duv, Ubig, Vbig)
%
[NbigU1, eta_u_big1, xi_u_big1]=size(Ubig);
[NbigV1, eta_v_big1, xi_v_big1]=size(Vbig);
if (ArrayBigSma3Duv.eta_u_big ~= eta_u_big1 || ...
    ArrayBigSma3Duv.xi_u_big ~= xi_u_big1 || ...
    NbigU1 ~= ArrayBigSma3Duv.Nbig)
  disp('size error between TotalArray.MSKbig_u and Ubig');
  keyboard;
end;
if (ArrayBigSma3Duv.eta_v_big ~= eta_v_big1 || ...
    ArrayBigSma3Duv.xi_v_big ~= xi_v_big1 || ...
    NbigV1 ~= ArrayBigSma3Duv.Nbig)
  disp('size error between TotalArray.MSKbig_v and Vbig');
  keyboard;
end;
%
UbigExp=Ubig(:);
VbigExp=Vbig(:);
UVbig=[UbigExp; VbigExp];
UVsma=ArrayBigSma3Duv.SPmat*UVbig;
SIZ_u_sma=ArrayBigSma3Duv.SIZ_u_sma;
SIZ_v_sma=ArrayBigSma3Duv.SIZ_v_sma;
SIZ_sma=ArrayBigSma3Duv.SIZ_sma;
UsmaExp=UVsma(1:SIZ_u_sma);
VsmaExp=UVsma(SIZ_u_sma+1:SIZ_sma);
%
Usma=reshape(...
    UsmaExp, ...
    ArrayBigSma3Duv.Nsma, ...
    ArrayBigSma3Duv.eta_u_sma, ...
    ArrayBigSma3Duv.xi_u_sma);
Vsma=reshape(...
    VsmaExp, ...
    ArrayBigSma3Duv.Nsma, ...
    ArrayBigSma3Duv.eta_v_sma, ...
    ArrayBigSma3Duv.xi_v_sma);
